apiVersion: v1
kind: Service
metadata:
  name: service1-srv
  namespace: example
spec:
  selector:
    app: service1
  type: NodePort
  ports:
    - name: service1
      port: 4001
      targetPort: 4001
      protocol: TCP
