apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deploy
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: yishaiz/k8s-service1
