apiVersion: v1
kind: Service
metadata:
  name: service2-srv
  namespace: example
spec:
  selector:
    app: service2
  type: NodePort
  ports:
    - name: service2
      port: 4002
      targetPort: 4002
      protocol: TCP
