apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: yishaiz/k8s-service2

---


apiVersion: v1
kind: Service
metadata:
  name: service2-srv
spec:
  selector:
    app: service2
  type: NodePort
  ports:
    - name: service2
      port: 4002
      targetPort: 4002
      protocol: TCP
